name: Genrate ASCII ART

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:           
        - name: checkout stage
          uses: actions/checkout@v4

        - name: Install Cowsay program
          run: sudo apt-get install cowsay -y

        - name: Execute cowsay CMD
          run: cowsay -f dragon "Run for cover, I am a DRAGON...RAWR" >> dragon.txt
        
        - name: Check file exists
          run: grep -i "dragon" dragon.txt

        - name: Read Dragon files
          run: cat dragon.txt
         
        - name: List All files
          run: ls -ltra  

        # - name: List files
        #   run: ls

        # - name: Read files
        #   run: cat README.md