name: Multi-Job-Pipeline

on: push

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:           
        - name: checkout stage
          uses: actions/checkout@v4

        - name: Install Cowsay program
          run: sudo apt-get install cowsay -y

        - name: Execute cowsay CMD
          run: cowsay -f dragon "Run for cover, I am a DRAGON...RAWR" >> dragon.txt
    
    test_job_2:
        runs-on: ubuntu-latest
        steps:      
        - name: Check file exists
          run: grep -i "dragon" dragon.txt
    
    deploy_job_3:
        runs-on: ubuntu-latest
        steps:  
        - name: Read Dragon files
          run: cat dragon.txt
         
        - name: List All files
          run: ls -ltra  

        # - name: List files
        #   run: ls

        # - name: Read files
        #   run: cat README.md